export const quizData1 = [
  {
    id: 1,
    question: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    answer: "Paris",
  },
  {
    id: 2,
    question: "What is the largest planet in our solar system?",
    options: ["Earth", "Jupiter", "Mars", "Saturn"],
    answer: "Jupiter",
  },
  {
    id: 3,
    question: "Who wrote 'To Kill a Mockingbird'?",
    options: [
      "Harper Lee",
      "Mark Twain",
      "Ernest Hemingway",
      "F. Scott Fitzgerald",
    ],
    answer: "Harper Lee",
  },
  {
    id: 4,
    question: "What is the chemical symbol for water?",
    options: ["H2O", "CO2", "O2", "NaCl"],
    answer: "H2O",
  },
  {
    id: 5,
    question: "What is the capital of Japan?",
    options: ["Seoul", "Beijing", "Tokyo", "Bangkok"],
    answer: "Tokyo",
  },
  {
    id: 6,
    question: "What is the largest mammal in the world?",
    options: ["Elephant", "Blue Whale", "Great White Shark", "Giraffe"],
    answer: "Blue Whale",
  },
  {
    id: 7,
    question: "What is the main ingredient in guacamole?",
    options: ["Tomato", "Avocado", "Onion", "Pepper"],
    answer: "Avocado",
  },
  {
    id: 8,
    question: "What is the smallest country in the world?",
    options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
    answer: "Vatican City",
  },
  {
    id: 9,
    question: "Who painted the Mona Lisa?",
    options: [
      "Vincent van Gogh",
      "Pablo Picasso",
      "Leonardo da Vinci",
      "Claude Monet",
    ],
    answer: "Leonardo da Vinci",
  },
  {
    id: 10,
    question: "What is the hardest natural substance on Earth?",
    options: ["Gold", "Diamond", "Iron", "Platinum"],
    answer: "Diamond",
  },
  {
    id: 11,
    question: "What is the largest ocean on Earth?",
    options: [
      "Atlantic Ocean",
      "Indian Ocean",
      "Arctic Ocean",
      "Pacific Ocean",
    ],
    answer: "Pacific Ocean",
  },
  {
    id: 12,
    question: "What is the main language spoken in Brazil?",
    options: ["Spanish", "Portuguese", "English", "French"],
    answer: "Portuguese",
  },
  {
    id: 13,
    question: "What is the capital of Canada?",
    options: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
    answer: "Ottawa",
  },
  {
    id: 14,
    question: "What is the largest desert in the world?",
    options: [
      "Sahara Desert",
      "Arabian Desert",
      "Gobi Desert",
      "Kalahari Desert",
    ],
    answer: "Sahara Desert",
  },
  {
    id: 15,
    question: "Who discovered penicillin?",
    options: [
      "Marie Curie",
      "Alexander Fleming",
      "Louis Pasteur",
      "Albert Einstein",
    ],
    answer: "Alexander Fleming",
  },
];
export const quizData2 = [
  {
    id: 1,
    question: "Which word is a noun?",
    options: ["Quickly", "Happiness", "Run", "Blue"],
    answer: "Happiness",
  },
  {
    id: 2,
    question: "Choose the correct past tense of 'go'.",
    options: ["Goed", "Went", "Go", "Gone"],
    answer: "Went",
  },
  {
    id: 3,
    question: "Which sentence is correct?",
    options: [
      "He go to school every day.",
      "He goes to school every day.",
      "He gone to school every day.",
      "He going to school every day.",
    ],
    answer: "He goes to school every day.",
  },
  {
    id: 4,
    question: "What is the opposite of 'hot'?",
    options: ["Cold", "Warm", "Cool", "Boiling"],
    answer: "Cold",
  },
  {
    id: 5,
    question: "Which one is a verb?",
    options: ["Table", "Eat", "Beautiful", "Quick"],
    answer: "Eat",
  },
  {
    id: 6,
    question: "Choose the correct article: 'I saw ___ elephant at the zoo.'",
    options: ["a", "an", "the", "no article"],
    answer: "an",
  },
  {
    id: 7,
    question: "What is the plural of 'child'?",
    options: ["Childs", "Children", "Childes", "Childer"],
    answer: "Children",
  },
  {
    id: 8,
    question: "Select the correct spelling:",
    options: ["Febuary", "Februery", "February", "Febrary"],
    answer: "February",
  },
  {
    id: 9,
    question: "Choose the synonym of 'happy':",
    options: ["Angry", "Sad", "Joyful", "Upset"],
    answer: "Joyful",
  },
  {
    id: 10,
    question: "Which sentence uses punctuation correctly?",
    options: [
      "Where are you",
      "Where are you.",
      "Where are you?",
      "Where are you!",
    ],
    answer: "Where are you?",
  },
  {
    id: 11,
    question: "Which word is an adjective?",
    options: ["Run", "Yellow", "Loudly", "Happily"],
    answer: "Yellow",
  },
  {
    id: 12,
    question: "What is the antonym of 'early'?",
    options: ["Quick", "Late", "Fast", "Soon"],
    answer: "Late",
  },
  {
    id: 13,
    question: "Choose the correct form: 'She ___ watching TV now.'",
    options: ["is", "are", "am", "be"],
    answer: "is",
  },
  {
    id: 14,
    question: "What is the comparative form of 'small'?",
    options: ["More small", "Smallest", "Smaller", "Most small"],
    answer: "Smaller",
  },
  {
    id: 15,
    question: "Which sentence is in the future tense?",
    options: [
      "She is playing tennis.",
      "She played tennis.",
      "She plays tennis.",
      "She will play tennis.",
    ],
    answer: "She will play tennis.",
  },
];

export const quizData3 = [
  {
    id: 1,
    question: "When did Bangladesh gain independence?",
    options: ["1947", "1971", "1965", "1975"],
    answer: "1971",
  },
  {
    id: 2,
    question: "What is the national flower of Bangladesh?",
    options: ["Rose", "Water Lily", "Marigold", "Sunflower"],
    answer: "Water Lily",
  },
  {
    id: 3,
    question: "What is the name of the national parliament building of Bangladesh?",
    options: [
     "Bangabhaban",
    "Jatiya Sangsad Bhaban",
    "Shilpakala Academy",
    "Suhrawardy Udyan",
    ],
    answer: "Jatiya Sangsad Bhaban",
  },
  {
    id: 4,
    question: "Which river is known as the longest in Bangladesh?",
    options: ["Padma", "Jamuna", "Meghna", "Brahmaputra"],
    answer: "Padma",
  },
  {
    id: 5,
    question: "What is the capital of Bangladesh?",
    options: ["Chittagong", "Dhaka", "Khulna", "Rajshahi"],
    answer: "Dhaka",
  },
  {
    id: 6,
    question: "Which is the largest district in Bangladesh by area?",
    options: ["Chittagong", "Khulna", "Rangamati", "Sylhet"],
    answer: "Rangamati",
  },
  {
    id: 7,
    question: "What is the national animal of Bangladesh?",
    options: ["Tiger", "Lion", "Elephant", "Deer"],
    answer: "Tiger",
  },
  {
    id: 8,
    question: "What is the name of the sea port in Bangladesh?",
    options: ["Cox’s Bazar", "Sundarbans", "Mongla", "Teknaf"],
    answer: "Mongla",
  },
  {
    id: 9,
    question: "Which city is known as the City of Mosques?",
    options: ["Comilla", "Sylhet", "Dhaka", "Barisal"],
    answer: "Dhaka",
  },
  {
    id: 10,
    question: "What is the currency of Bangladesh?",
    options: ["Rupee", "Dollar", "Taka", "Riyal"],
    answer: "Taka",
  },
  {
    id: 11,
    question: "Which year was the Language Movement in Bangladesh?",
    options: ["1947", "1952", "1971", "1962"],
    answer: "1952",
  },
  {
    id: 12,
    question: "Which crop is known as the staple food of Bangladesh?",
    options: ["Wheat", "Corn", "Rice", "Potato"],
    answer: "Rice",
  },
  {
    id: 13,
    question: "Which is the only UNESCO World Heritage Site in Bangladesh?",
    options: ["Lalbagh Fort", "Mahasthangarh", "Sundarbans", "Ahsan Manzil"],
    answer: "Sundarbans",
  },
  {
    id: 14,
    question: "Which is the highest peak in Bangladesh?",
    options: ["Keokradong", "Tajingdong", "Chimbuk", "Saka Haphong"],
    answer: "Saka Haphong",
  },
  {
    id: 15,
    question: "What is the national fruit of Bangladesh?",
    options: ["Banana", "Mango", "Jackfruit", "Litchi"],
    answer: "Jackfruit",
  },
];


